export const REGISTER_SUCCESS = 'REGISTER_SUCCES';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const SET_DA_PHONE_NUMBER = 'SET_DA_PHONE_NUMBER';
export const SET_DA_IMAGE_URL = 'SET_DA_IMAGE_URL';
export const SET_DA_ANIMAL_CATEGORY = 'SET_DA_ANIMAL_CATEGORY';
export const SET_DA_LOCATION = 'SET_DA_LOCATION';
export const SET_DA_COMMUNITY = 'SET_DA_COMMUNITY';
export const SET_DA_COMMUNITY_LIST = 'SET_DA_COMMUNITY_LIST';

export const SET_AR_ANIMAL_TYPE = 'SET_AR_ANIMAL_TYPE';
export const SET_AR_ANIMAL_NAME = 'SET_AR_ANIMAL_NAME';
export const SET_AR_IMAGE_URL = 'SET_AR_IMAGE_URL';
export const SET_AR_ADD_INFO = 'SET_AR_ADD_INFO';
export const SET_AR_NAME = 'SET_AR_NAME';
export const SET_AR_EMAIL = 'SET_AR_EMAIL';
export const SET_AR_PHONE_NUMBER = 'SET_AR_PHONE_NUMBER';
export const SET_AR_ADDRESS = 'SET_AR_ADDRESS';
export const SET_AR_PROVINCE = 'SET_AR_PROVINCE';
export const SET_AR_CITY = 'SET_AR_CITY';
export const SET_AR_COMMUNITY = 'SET_AR_COMMUNITY';
export const SET_AR_COMMUNITY_LIST = 'SET_AR_COMMUNITY_LIST';

export const REPORT_SENT = 'REPORT_SENT';